FROM ubuntu:22.04

# set proxy
# ARG http_proxy=http://10.55.123.98:3333
# ARG https_proxy=http://10.55.123.98:3333

RUN \
  export DEBIAN_FRONTEND=noninteractive; \
  apt-get -y update; \
  apt-get -y upgrade; \
  apt-get -y install \
    pkg-config \
    build-essential \
    ca-certificates \
    wget \
    xvfb \
    libglfw3-dev \
    libuv1-dev \
    libjpeg-turbo8-dev \
    libicu-dev \
    libopengl-dev \
    libgif-dev \
    libpng-dev \
    libwebp-dev \
    libcurl4-openssl-dev; \
  apt-get -y --purge autoremove; \
  apt-get clean; \
  rm -rf /var/lib/apt/lists/*;

RUN \
  wget -q https://nodejs.org/download/release/v22.9.0/node-v22.9.0-linux-x64.tar.xz; \
  mkdir -p /usr/local/lib/nodejs && tar -xJf node-v22.9.0-linux-x64.tar.xz --strip-components=1 -C /usr/local/lib/nodejs; \
  rm -rf node-v22.9.0-linux-x64.tar.xz;

ENV PATH=/usr/local/lib/nodejs/bin:$PATH

WORKDIR /tile-server

ADD . .

RUN \
  npm install -g yarn; \
  yarn;

CMD ["sleep", "infinity"]
